menu:
 Home: /
 Archive: /archives
 Tags: /tags/
 Techblog: http://lydsnm.top
 RSS: /atom.xml
 About: /about/

widgets:
 - greeting
 - site_links

rss: /atom.xml

readMore: 查看全文

feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:

tag_generator:
  per_page: 10
